---
- name: Copy over check_mk agent
  copy: src=files/check-mk-agent-1.2.6p16-1.noarch.rpm dest=/tmp/

- name: Install xinetd
  yum: name=xinetd state=latest update_cache=yes

- name: Install check_mk agent
  yum: name=/tmp/check-mk-agent-1.2.6p16-1.noarch.rpm state=present register=result
  notify:
    - restart xinetd
